-- Enterprise Multi-Tenant Runtime Sprint 3 evidence-table completion hotfix
-- Forward-only migration: completes tenant_route_isolation_reviews so it mirrors TENANT_ROUTE_REGISTRY.
-- Does not change Sprint 3 route behavior, route classifications, or tenant schema shape.
-- Does not disable triggers and does not rewrite already-tagged migrations 0028, 0029, or 0030.

insert into tenant_route_isolation_reviews(route_file, route_family, tenant_scope_status, boundary_mode, evidence_code, review_status, notes)
values
  ('apps/api/src/routes/assets.ts', 'Asset register and asset detail workspace', 'tenant_scoped', 'runtime_filter', 'MT-S3-003', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-003.'),
  ('apps/api/src/routes/evidence.ts', 'Evidence room, signed URL, and evidence linkage', 'tenant_scoped', 'runtime_filter_and_object_boundary', 'MT-S3-004', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-004.'),
  ('apps/api/src/routes/reports.ts', 'Report builder, export, and issue gates', 'tenant_scoped', 'runtime_filter_and_object_boundary', 'MT-S3-005', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-005.'),
  ('apps/api/src/routes/inspections.ts', 'Inspection events and inspection package readiness', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/ndt.ts', 'NDT measurement create/import/read APIs', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/ndt-data-room.ts', 'NDT data room visualization and drilldown', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/findings.ts', 'Findings and anomaly lifecycle', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/calculations.ts', 'Calculation runs and deterministic calculation snapshots', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/engineering-reviews.ts', 'Engineering review approvals and reviewer gates', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/integrity-decisions.ts', 'Integrity decision records and dispositions', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/work-orders.ts', 'Internal work orders and closure readiness', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/ffs.ts', 'FFS case workflow', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/rbi.ts', 'RBI workflow and risk ranking interface', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/integrity-workspace.ts', 'End-to-end integrity workspace consolidation', 'tenant_scoped', 'runtime_filter', 'MT-S3-006', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-006.'),
  ('apps/api/src/routes/audit-logs.ts', 'Audit log visibility', 'tenant_scoped', 'runtime_filter', 'MT-S3-007', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-007.'),
  ('apps/api/src/routes/governance-dashboard.ts', 'Governance dashboard aggregation', 'tenant_scoped', 'runtime_filter', 'MT-S3-007', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-007.'),
  ('apps/api/src/routes/workflow-console.ts', 'n8n workflow console visibility', 'tenant_scoped', 'runtime_filter', 'MT-S3-007', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-007.'),
  ('apps/api/src/routes/ai-extraction.ts', 'AI extraction staging and promotion governance', 'tenant_scoped', 'runtime_filter', 'MT-S3-007', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-007.'),
  ('apps/api/src/routes/engineering-validation.ts', 'Engineering validation and validation case execution', 'tenant_scoped', 'runtime_filter', 'MT-S3-007', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-007.'),
  ('apps/api/src/routes/formulas.ts', 'Formula registry and version governance', 'global_system', 'system_observability_boundary', 'MT-S3-008', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-008.'),
  ('apps/api/src/routes/tenants.ts', 'Tenant context and tenant isolation health', 'tenant_control_plane', 'tenant_context_control_plane', 'MT-S3-008', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-008.'),
  ('apps/api/src/routes/admin-governance.ts', 'Admin governance console', 'global_system', 'system_observability_boundary', 'MT-S3-008', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-008.'),
  ('apps/api/src/routes/security-monitoring.ts', 'Security monitoring and security events', 'global_system', 'system_observability_boundary', 'MT-S3-008', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-008.'),
  ('apps/api/src/routes/operations.ts', 'Operations readiness and support controls', 'global_system', 'system_observability_boundary', 'MT-S3-008', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-008.'),
  ('apps/api/src/routes/production-validation.ts', 'Production validation and go-live evidence', 'global_system', 'system_observability_boundary', 'MT-S3-008', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-008.'),
  ('apps/api/src/routes/golive-readiness.ts', 'Go-live readiness and hypercare readiness', 'global_system', 'system_observability_boundary', 'MT-S3-008', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-008.'),
  ('apps/api/src/routes/release-closure.ts', 'Release closure and final evidence records', 'global_system', 'system_observability_boundary', 'MT-S3-008', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-008.'),
  ('apps/api/src/routes/auth.ts', 'Authentication and session context', 'auth_context', 'auth_session_boundary', 'MT-S3-009', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-009.'),
  ('apps/api/src/routes/rbac-demo.ts', 'Local RBAC demo route', 'local_demo_only', 'local_demo_non_production', 'MT-S3-009', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-009.'),
  ('apps/api/src/routes/health.ts', 'Health checks', 'public_health', 'public_no_tenant_data', 'MT-S3-009', 'pending', 'Sprint 3 evidence-table completion hotfix mirrors TENANT_ROUTE_REGISTRY for full route-family review coverage; route evidence MT-S3-009.')
on conflict(route_file) do update set
  route_family = excluded.route_family,
  tenant_scope_status = excluded.tenant_scope_status,
  boundary_mode = excluded.boundary_mode,
  evidence_code = excluded.evidence_code,
  notes = excluded.notes,
  updated_at = now();
