import type { FormulaLibraryTestCase } from './formula-types.js';

export const FORMULA_LIBRARY_TEST_CASES: FormulaLibraryTestCase[] = [
  {
    test_case_id: 'TC-001',
    test_case_name: 'Normal corrosion rate',
    formula_set: 'shell_thickness_mvp_v1',
    asset_tag: 'TANK-T-02',
    component: 'SHELL_COURSE_1',
    previous_thickness_mm: 10.0,
    current_thickness_mm: 9.0,
    minimum_required_thickness_mm: 6.0,
    years_between_inspections: 5.0,
    reading_unit: 'mm',
    evidence_code: 'EVD-2026-000001',
    expected_corrosion_rate_mm_y: 0.2,
    expected_remaining_life_y: 15.0,
    expected_status: 'OK',
    expected_warning_code: null,
    purpose: 'Normal positive corrosion rate and remaining life.',
    priority: 'high',
  },
  {
    test_case_id: 'TC-002',
    test_case_name: 'Thickness below minimum',
    formula_set: 'shell_thickness_mvp_v1',
    asset_tag: 'TANK-T-02',
    component: 'SHELL_COURSE_1',
    previous_thickness_mm: 10.0,
    current_thickness_mm: 5.8,
    minimum_required_thickness_mm: 6.0,
    years_between_inspections: 5.0,
    reading_unit: 'mm',
    evidence_code: 'EVD-2026-000002',
    expected_corrosion_rate_mm_y: 0.84,
    expected_remaining_life_y: -0.238095,
    expected_status: 'BELOW_MIN_REVIEW',
    expected_warning_code: 'CURRENT_BELOW_MINIMUM_REQUIRED_THICKNESS',
    purpose: 'Current thickness below minimum must block final-use status.',
    priority: 'critical',
  },
  {
    test_case_id: 'TC-003',
    test_case_name: 'Zero corrosion rate',
    formula_set: 'shell_thickness_mvp_v1',
    asset_tag: 'TANK-T-02',
    component: 'SHELL_COURSE_1',
    previous_thickness_mm: 9.0,
    current_thickness_mm: 9.0,
    minimum_required_thickness_mm: 6.0,
    years_between_inspections: 5.0,
    reading_unit: 'mm',
    evidence_code: 'EVD-2026-000003',
    expected_corrosion_rate_mm_y: 0.0,
    expected_remaining_life_y: 'N/A',
    expected_status: 'OK_ZERO_RATE_REVIEW',
    expected_warning_code: 'ZERO_CORROSION_RATE_REVIEW_REQUIRED',
    purpose: 'Zero corrosion rate must avoid divide-by-zero and require review.',
    priority: 'high',
  },
  {
    test_case_id: 'TC-004',
    test_case_name: 'Negative corrosion rate',
    formula_set: 'shell_thickness_mvp_v1',
    asset_tag: 'TANK-T-02',
    component: 'SHELL_COURSE_1',
    previous_thickness_mm: 8.5,
    current_thickness_mm: 9.0,
    minimum_required_thickness_mm: 6.0,
    years_between_inspections: 5.0,
    reading_unit: 'mm',
    evidence_code: 'EVD-2026-000004',
    expected_corrosion_rate_mm_y: -0.1,
    expected_remaining_life_y: 'N/A',
    expected_status: 'DATA_REVIEW_REQUIRED',
    expected_warning_code: 'NEGATIVE_CORROSION_RATE_REVIEW_REQUIRED',
    purpose: 'Current thickness greater than previous thickness indicates data/evidence/unit/timing issue.',
    priority: 'high',
  },
  {
    test_case_id: 'TC-005',
    test_case_name: 'Missing previous thickness',
    formula_set: 'shell_thickness_mvp_v1',
    asset_tag: 'TANK-T-02',
    component: 'SHELL_COURSE_1',
    previous_thickness_mm: null,
    current_thickness_mm: 9.0,
    minimum_required_thickness_mm: 6.0,
    years_between_inspections: 5.0,
    reading_unit: 'mm',
    evidence_code: 'EVD-2026-000005',
    expected_corrosion_rate_mm_y: null,
    expected_remaining_life_y: 'N/A',
    expected_status: 'INCOMPLETE_INPUT',
    expected_warning_code: 'MISSING_PREVIOUS_THICKNESS',
    purpose: 'Missing previous thickness prevents corrosion-rate calculation.',
    priority: 'critical',
  },
  {
    test_case_id: 'TC-006',
    test_case_name: 'Missing evidence',
    formula_set: 'shell_thickness_mvp_v1',
    asset_tag: 'TANK-T-02',
    component: 'SHELL_COURSE_1',
    previous_thickness_mm: 10.0,
    current_thickness_mm: 9.0,
    minimum_required_thickness_mm: 6.0,
    years_between_inspections: 5.0,
    reading_unit: 'mm',
    evidence_code: null,
    expected_corrosion_rate_mm_y: 0.2,
    expected_remaining_life_y: 15.0,
    expected_status: 'BLOCKED_MISSING_EVIDENCE',
    expected_warning_code: 'MISSING_EVIDENCE_REFERENCE',
    purpose: 'Numeric calculation may be possible, but promotion/final use must be blocked without evidence.',
    priority: 'critical',
  },
  {
    test_case_id: 'TC-007',
    test_case_name: 'Remaining life below threshold',
    formula_set: 'shell_thickness_mvp_v1',
    asset_tag: 'TANK-T-02',
    component: 'SHELL_COURSE_1',
    previous_thickness_mm: 10.0,
    current_thickness_mm: 6.3,
    minimum_required_thickness_mm: 6.0,
    years_between_inspections: 5.0,
    reading_unit: 'mm',
    evidence_code: 'EVD-2026-000007',
    expected_corrosion_rate_mm_y: 0.74,
    expected_remaining_life_y: 0.405405,
    expected_status: 'ACTION_REQUIRED',
    expected_warning_code: 'REMAINING_LIFE_BELOW_MVP_THRESHOLD',
    purpose: 'Remaining life below threshold must trigger action-required status.',
    priority: 'critical',
  },
  {
    test_case_id: 'TC-008',
    test_case_name: 'Unit mismatch warning',
    formula_set: 'shell_thickness_mvp_v1',
    asset_tag: 'TANK-T-02',
    component: 'SHELL_COURSE_1',
    previous_thickness_mm: null,
    current_thickness_mm: null,
    minimum_required_thickness_mm: null,
    years_between_inspections: 5.0,
    reading_unit: 'inch',
    evidence_code: 'EVD-2026-000008',
    expected_corrosion_rate_mm_y: null,
    expected_remaining_life_y: 'N/A',
    expected_status: 'UNIT_REVIEW_REQUIRED',
    expected_warning_code: 'UNIT_MISMATCH',
    purpose: 'Unit mismatch must block final use until engineer confirms conversion basis.',
    priority: 'critical',
  },
];
